# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('AU', 'Автозаводский'), ('KNV', 'Канавинский'), ('LEN', 'Ленинский'), ('MSK', 'Московский'), ('NN', 'Нижегородский'), ('PRIOK', 'Приокский'), ('SOV', 'Советский'), ('SOR', 'Сормовский')], default='AU', max_length=20)),
                ('rooms', models.CharField(choices=[('1', '1 комната'), ('2', '2 комнаты'), ('3', '3 комнаты'), ('3+', 'более 3 комнат')], default='1 комната', max_length=20)),
                ('floor', models.CharField(choices=[('first', 'первый этаж'), ('middle', 'средний этаж'), ('last', 'последний этаж')], default='первый этаж', max_length=20)),
                ('wall_material', models.CharField(choices=[('kirp', 'кирпич'), ('pan', 'панель'), ('nd', 'нет данных')], default='нет данных', max_length=20)),
                ('remont', models.CharField(choices=[('vip', 'дизайнерский проект'), ('euro', 'евроремонт'), ('tip', 'типовой'), ('nado', 'требуется')], default='tip', max_length=20)),
                ('parking', models.CharField(choices=[('yes', 'во дворе'), ('no', 'нет'), ('hz', 'нет данных')], default='hz', max_length=20)),
                ('lift', models.CharField(choices=[('yes', 'есть'), ('no', 'нет'), ('hz', 'нет данных')], default='hz', max_length=20)),
            ],
        ),
    ]
