# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtest', '0003_auto_20180619_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='floor',
            field=models.CharField(choices=[('first', 'первый этаж'), ('middle', 'средний этаж'), ('last', 'последний этаж')], default='первый этаж', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='lift',
            field=models.CharField(choices=[('yes', 'есть'), ('no', 'нет'), ('hz', '')], default='hz', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='parking',
            field=models.CharField(choices=[('yes', 'во дворе'), ('no', 'нет'), ('hz', '')], default='hz', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='remont',
            field=models.CharField(choices=[('vip', 'дизайнерский проект'), ('euro', 'евроремонт'), ('tip', 'типовой'), ('nado', 'требуется')], default='tip', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='rooms',
            field=models.CharField(choices=[('1', '1 комната'), ('2', '2 комнаты'), ('3', '3 комнаты'), ('3+', 'более 3 комнат')], default='1 комната', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='wall_material',
            field=models.CharField(choices=[('kirp', 'кирпич'), ('pan', 'панель'), ('nd', '')], default='нет данных', max_length=20),
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.CharField(choices=[('AU', 'Автозаводский'), ('KNV', 'Канавинский'), ('LEN', 'Ленинский'), ('MSK', 'Московский'), ('NN', 'Нижегородский'), ('PRIOK', 'Приокский'), ('SOV', 'Советский'), ('SOR', 'Сормовский')], default='AU', max_length=20),
        ),
    ]
